/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.projeto.form;

import br.projeto.DAO.OrcamentoDAO;
import br.projeto.DAO.PecaDAO;
import br.projeto.data.Peca;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Igor
 */
public class FrmOS extends javax.swing.JFrame {

    Calendar c = Calendar.getInstance();
    DateFormat data = DateFormat.getDateInstance();

    /**
     * Creates new form FrmOS
     */
    public FrmOS() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbrirOS = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        frmCel1 = new javax.swing.JFormattedTextField();
        frmCel2 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        frmAtendente = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        frmTotalPecas = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        frmTotalObra = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        frmOrcamentoFinal = new javax.swing.JFormattedTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        RemoverPecaOrcamento = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        frmDefeito = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        frmObs1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        frmStatus = new javax.swing.JComboBox<>();
        LimparCampos = new javax.swing.JButton();
        frmNomeCliente = new javax.swing.JFormattedTextField();
        InserePecas = new javax.swing.JButton();
        LimparPecas = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        frmPlacaVeiculo = new javax.swing.JFormattedTextField();
        frmModeloVeiculo = new javax.swing.JFormattedTextField();
        Selecionar = new javax.swing.JButton();
        ConsultaPecas = new javax.swing.JButton();
        frmPecas = new javax.swing.JTextField();
        AtualizaOrcamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        AbrirOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AbrirOS.setText("Abrir OS");

        Alterar.setText("Alterar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cliente");

        Pesquisar.setText("Pesquisar");

        Excluir.setText("Excluir");

        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        frmCel1.setEditable(false);
        frmCel1.setBackground(java.awt.SystemColor.controlHighlight);
        frmCel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            frmCel1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        frmCel2.setEditable(false);
        frmCel2.setBackground(java.awt.SystemColor.controlHighlight);
        frmCel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            frmCel2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Celular 1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Celular 2");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Veiculo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Observação");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Descrição do problema");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Peças");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da Peça", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDropMode(javax.swing.DropMode.ON);
        jTable1.setGridColor(new java.awt.Color(255, 255, 204));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Atendente");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da Peça", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setDropMode(javax.swing.DropMode.ON);
        jTable2.setGridColor(new java.awt.Color(255, 255, 204));
        jTable2.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable2);

        frmAtendente.setEditable(true);
        frmAtendente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frmAtendente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        frmTotalPecas.setEditable(false);
        frmTotalPecas.setBackground(new java.awt.Color(255, 255, 255));
        frmTotalPecas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frmTotalPecas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        frmTotalPecas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        frmTotalPecas.setEnabled(false);
        frmTotalPecas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Total das peças:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mão de obra:");

        frmTotalObra.setEditable(false);
        frmTotalObra.setBackground(new java.awt.Color(255, 255, 255));
        frmTotalObra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frmTotalObra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        frmTotalObra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        frmTotalObra.setEnabled(false);
        frmTotalObra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Orçamento final:");

        frmOrcamentoFinal.setEditable(false);
        frmOrcamentoFinal.setBackground(new java.awt.Color(255, 255, 255));
        frmOrcamentoFinal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frmOrcamentoFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        frmOrcamentoFinal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        frmOrcamentoFinal.setEnabled(false);
        frmOrcamentoFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da Peça", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setDropMode(javax.swing.DropMode.ON);
        jTable3.setGridColor(new java.awt.Color(255, 255, 204));
        jTable3.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jTable3.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable3PropertyChange(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);

        RemoverPecaOrcamento.setBackground(new java.awt.Color(255, 255, 255));
        RemoverPecaOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/form/iconmonstr-x-mark-cinza.png"))); // NOI18N
        RemoverPecaOrcamento.setToolTipText("Para remover ltens do orçamento");
        RemoverPecaOrcamento.setAlignmentX(0.5F);
        RemoverPecaOrcamento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/form/iconmonstr-x-mark-2.png"))); // NOI18N
        RemoverPecaOrcamento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/form/iconmonstr-x-mark-2.png"))); // NOI18N
        RemoverPecaOrcamento.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/form/iconmonstr-x-mark-vermelho.png"))); // NOI18N
        RemoverPecaOrcamento.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/br/projeto/form/iconmonstr-x-mark-vermelho.png"))); // NOI18N
        RemoverPecaOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverPecaOrcamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frmTotalPecas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frmTotalObra, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frmOrcamentoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoverPecaOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RemoverPecaOrcamento)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frmTotalPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frmTotalObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frmOrcamentoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frmDefeito.setColumns(20);
        frmDefeito.setLineWrap(true);
        frmDefeito.setRows(5);
        frmDefeito.setWrapStyleWord(true);
        jScrollPane3.setViewportView(frmDefeito);

        frmObs1.setColumns(20);
        frmObs1.setLineWrap(true);
        frmObs1.setRows(5);
        frmObs1.setWrapStyleWord(true);
        jScrollPane4.setViewportView(frmObs1);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Status da Ordem de Serviço:");

        frmStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frmStatus.setMaximumRowCount(3);
        frmStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGUARDANDO", "FINALIZADA", "NÃO AUTORIZADA" }));
        frmStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmStatusActionPerformed(evt);
            }
        });

        LimparCampos.setText("Limpar Todos os Campos");
        LimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCamposActionPerformed(evt);
            }
        });

        frmNomeCliente.setEditable(false);
        frmNomeCliente.setBackground(java.awt.SystemColor.controlHighlight);
        frmNomeCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frmNomeCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        InserePecas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        InserePecas.setText("Inserir Peça no Orçamento");
        InserePecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserePecasActionPerformed(evt);
            }
        });

        LimparPecas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LimparPecas.setForeground(new java.awt.Color(51, 51, 51));
        LimparPecas.setText("Limpar Peças");
        LimparPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparPecasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Placa do veículo");

        frmPlacaVeiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frmPlacaVeiculo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        frmModeloVeiculo.setEditable(false);
        frmModeloVeiculo.setBackground(java.awt.SystemColor.controlHighlight);
        frmModeloVeiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frmModeloVeiculo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        Selecionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Selecionar.setText("Selecionar");
        Selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarActionPerformed(evt);
            }
        });

        ConsultaPecas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaPecas.setText("Consultar");
        ConsultaPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPecasActionPerformed(evt);
            }
        });

        frmPecas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        AtualizaOrcamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AtualizaOrcamento.setText("Atualizar Orçamento");
        AtualizaOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizaOrcamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(13, 13, 13)
                                        .addComponent(frmPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Selecionar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(frmNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(frmModeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(frmCel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(frmCel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(AbrirOS)
                                .addGap(18, 18, 18)
                                .addComponent(Alterar)
                                .addGap(18, 18, 18)
                                .addComponent(Pesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(Excluir)
                                .addGap(18, 18, 18)
                                .addComponent(LimparCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Fechar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(frmPecas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ConsultaPecas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(frmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InserePecas)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(AtualizaOrcamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LimparPecas)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(frmAtendente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frmNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(frmPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(frmModeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Selecionar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frmCel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frmCel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(frmPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ConsultaPecas))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InserePecas)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LimparPecas)
                    .addComponent(AtualizaOrcamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(frmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(frmAtendente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fechar)
                    .addComponent(Excluir)
                    .addComponent(Pesquisar)
                    .addComponent(Alterar)
                    .addComponent(AbrirOS)
                    .addComponent(Cadastrar)
                    .addComponent(LimparCampos))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed

    }//GEN-LAST:event_CadastrarActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharActionPerformed

    private void LimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCamposActionPerformed
        frmPlacaVeiculo.setText("");
        frmNomeCliente.setText("");
        frmCel1.setText("");
        frmCel2.setText("");
        frmAtendente.setSelectedIndex(-1);
        frmAtendente.removeAllItems();
        frmModeloVeiculo.setText("");
        frmPecas.setText("");
        frmStatus.setSelectedIndex(-1);
        frmTotalPecas.setText("");
        frmTotalObra.setText("");
        frmOrcamentoFinal.setText("");
        frmDefeito.setText("");
        frmObs1.setText("");

        DefaultTableModel modeloTabela = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel modeloTabela2 = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel modeloTabela3 = (DefaultTableModel) jTable3.getModel();
        // coloca a tabela em uma variável do tipo DefaultTableModel, que permite a modelagem dos dados da tabela

        for (int i = modeloTabela.getRowCount() - 1; i >= 0; i--) {
            modeloTabela.removeRow(i);
            // loop que limpa a tabela
        }
        for (int i = modeloTabela2.getRowCount() - 1; i >= 0; i--) {
            modeloTabela2.removeRow(i);
            // loop que limpa a tabela
        }
        for (int i = modeloTabela3.getRowCount() - 1; i >= 0; i--) {
            modeloTabela2.removeRow(i);
            // loop que limpa a tabela
        }

    }//GEN-LAST:event_LimparCamposActionPerformed

    private void frmStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmStatusActionPerformed

    private void LimparPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparPecasActionPerformed
        frmPecas.setText("");

        DefaultTableModel modeloTabela = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel modeloTabela2 = (DefaultTableModel) jTable2.getModel();
        // coloca a tabela em uma variável do tipo DefaultTableModel, que permite a modelagem dos dados da tabela

        for (int i = modeloTabela.getRowCount() - 1; i >= 0; i--) {
            modeloTabela.removeRow(i);
            // loop que limpa a tabela
        }
        for (int i = modeloTabela2.getRowCount() - 1; i >= 0; i--) {
            modeloTabela2.removeRow(i);
            // loop que limpa a tabela
        }
    }//GEN-LAST:event_LimparPecasActionPerformed

    private void InserePecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserePecasActionPerformed
        addPecas();
    }//GEN-LAST:event_InserePecasActionPerformed

    private void SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarActionPerformed

    }//GEN-LAST:event_SelecionarActionPerformed

    private void ConsultaPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPecasActionPerformed
        listaPecas();
    }//GEN-LAST:event_ConsultaPecasActionPerformed

    private void AtualizaOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizaOrcamentoActionPerformed
        orcamentoPecas();
    }//GEN-LAST:event_AtualizaOrcamentoActionPerformed

    private void jTable3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable3PropertyChange
        DefaultTableModel modeloTabela3 = (DefaultTableModel) jTable3.getModel();
        modeloTabela3.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                
                totalOrcamento();
            }
        });
    }//GEN-LAST:event_jTable3PropertyChange

    private void RemoverPecaOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverPecaOrcamentoActionPerformed
        
    }//GEN-LAST:event_RemoverPecaOrcamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOS().setVisible(true);
            }
        });
    }

    public void calendario() {

//        c.set(Calendar.YEAR, 1995);
//        c.set(Calendar.MONTH, Calendar.MARCH);
//        c.set(Calendar.DAY_OF_MONTH, 20);
        System.out.println("Data/Hora atual: " + c.getTime());
        System.out.println("Ano: " + c.get(Calendar.YEAR));
        System.out.println("Mês: " + c.get(Calendar.MONTH));
        System.out.println("Dia do Mês: " + c.get(Calendar.DAY_OF_MONTH));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirOS;
    private javax.swing.JButton Alterar;
    private javax.swing.JButton AtualizaOrcamento;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton ConsultaPecas;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Fechar;
    private javax.swing.JButton InserePecas;
    private javax.swing.JButton LimparCampos;
    private javax.swing.JButton LimparPecas;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton RemoverPecaOrcamento;
    private javax.swing.JButton Selecionar;
    private javax.swing.JComboBox<String> frmAtendente;
    private javax.swing.JFormattedTextField frmCel1;
    private javax.swing.JFormattedTextField frmCel2;
    private javax.swing.JTextArea frmDefeito;
    private javax.swing.JFormattedTextField frmModeloVeiculo;
    private javax.swing.JFormattedTextField frmNomeCliente;
    private javax.swing.JTextArea frmObs1;
    private javax.swing.JFormattedTextField frmOrcamentoFinal;
    private javax.swing.JTextField frmPecas;
    private javax.swing.JFormattedTextField frmPlacaVeiculo;
    private javax.swing.JComboBox<String> frmStatus;
    private javax.swing.JFormattedTextField frmTotalObra;
    private javax.swing.JFormattedTextField frmTotalPecas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
    public void listaPecas() {
        try {
            PecaDAO pDAO = new PecaDAO();

            DefaultTableModel modeloTabela = (DefaultTableModel) jTable1.getModel();
            // coloca a tabela em uma variável do tipo DefaultTableModel, que permite a modelagem dos dados da tabela

            if (frmPecas.getText().isEmpty()) {

                ArrayList<Peca> todasp = pDAO.consultaTodasPecas();

                for (int i = modeloTabela.getRowCount() - 1; i >= 0; i--) {
                    modeloTabela.removeRow(i);
                    // loop que limpa a tabela antes de ser atualizada
                }
                for (int i = 0; i < todasp.size(); i++) {
                    // loop que pega os dados e insere na tabela
                    Object[] dados = new Object[4]; // instancia os objetos. Cada objeto representa um atributo
                    dados[0] = todasp.get(i).getNome_pecas();
                    dados[1] = todasp.get(i).getValor_pecas();
                    dados[2] = todasp.get(i).getQuantidade_pecas();

                    // pega os dados salvos do banco de dados (que estão nas variáveis) e os coloca nos objetos definidos
                    modeloTabela.addRow(dados); // insere uma linha nova a cada item novo encontrado na tabela do BD
                }
            } else {
                ArrayList<Peca> p = pDAO.consultaValorPecas(frmPecas.getText());

                for (int i = modeloTabela.getRowCount() - 1; i >= 0; i--) {
                    modeloTabela.removeRow(i);
                    // loop que limpa a tabela antes de ser atualizada
                }
                for (int i = 0; i < p.size(); i++) {
                    // loop que pega os dados e insere na tabela
                    Object[] dados = new Object[4]; // instancia os objetos. Cada objeto representa um atributo
                    dados[0] = p.get(i).getNome_pecas();
                    dados[1] = p.get(i).getValor_pecas();
                    dados[2] = p.get(i).getQuantidade_pecas();

                    // pega os dados salvos do banco de dados (que estão nas variáveis) e os coloca nos objetos definidos
                    modeloTabela.addRow(dados); // insere uma linha nova a cada item novo encontrado na tabela do BD
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro no processo!\n" + ex.getMessage(), "Consulta de Peças", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addPecas() {
        DefaultTableModel modeloTabela3 = (DefaultTableModel) jTable3.getModel();

        String selectedNome = null;
        double selectedValor = 0;
        int selectedQtd = 0;

        int qtdLinhasSelecionadas = jTable1.getSelectedRowCount();
        int[] selectedRow = jTable1.getSelectedRows();

        for (int i = selectedRow.length - 1; i >= 0; i--) {
            selectedNome = (String) jTable1.getValueAt(jTable1.convertRowIndexToModel(selectedRow[i]), 0);
            selectedValor = (double) jTable1.getValueAt(jTable1.convertRowIndexToModel(selectedRow[i]), 1);
            selectedQtd = (int) jTable1.getValueAt(jTable1.convertRowIndexToModel(selectedRow[i]), 2);
        }

        for (int i = 0; i < qtdLinhasSelecionadas; i++) {

            // loop que pega os dados e insere na tabela
            Object[] dados = new Object[3]; // instancia os objetos. Cada objeto representa um atributo
            dados[0] = selectedNome;
            dados[1] = selectedValor;
            dados[2] = selectedQtd;
            modeloTabela3.addRow(dados); // insere uma linha nova a cada item novo encontrado na tabela do BD
        }
        //System.out.println("Nome " + selectedNome + "\nValor " + selectedValor + "\nQuantidade " + selectedQtd);
    }

    public void orcamentoPecas() {

        DefaultTableModel modeloTabela3 = (DefaultTableModel) jTable3.getModel();

        String selectedNome = null;
        double selectedValor = 0;
        int selectedQtd = 0;
        
        int qtdLinhasSelecionadas = jTable2.getSelectedRowCount();
        int[] selectedRow = jTable2.getSelectedRows();

        for (int i = selectedRow.length - 1; i >= 0; i--) {
            selectedNome = (String) jTable2.getValueAt(jTable2.convertRowIndexToModel(selectedRow[i]), 0);
            selectedValor = (double) jTable2.getValueAt(jTable2.convertRowIndexToModel(selectedRow[i]), 1);
            selectedQtd = (int) jTable2.getValueAt(jTable2.convertRowIndexToModel(selectedRow[i]), 2);
        }
        for (int i = 0; i < qtdLinhasSelecionadas; i++) {

            // loop que pega os dados e insere na tabela
            Object[] dados = new Object[3]; // instancia os objetos. Cada objeto representa um atributo
            dados[0] = selectedNome;
            dados[1] = selectedValor;
            dados[2] = selectedQtd;
            modeloTabela3.addRow(dados); // insere uma linha nova a cada item novo encontrado na tabela do BD
        }
    }

    public void totalOrcamento() {
        String selectedNome = null;

        double selectedValor = 0;
        int selectedQtd = 0;
        double valorTotalPecas = 0;
        double maoDeObra = 50.0;
        double orcamento = 0;
        jTable3.selectAll();
        int[] selectedRow = jTable3.getSelectedRows();
        int qtdLinhasSelecionadas = jTable3.getSelectedRowCount();

        for (int i = selectedRow.length - 1; i >= 0; i--) {
            selectedNome = (String) jTable3.getValueAt(jTable3.convertRowIndexToModel(selectedRow[i]), 0);
            selectedValor = (double) jTable3.getValueAt(jTable3.convertRowIndexToModel(selectedRow[i]), 1);
            selectedQtd = (int) jTable3.getValueAt(jTable3.convertRowIndexToModel(selectedRow[i]), 2);

            for (int x = 0; x < qtdLinhasSelecionadas; x++) {
                for (int j = 0; j <= selectedQtd; j++) {
                    maoDeObra = maoDeObra * 0.2;
                }
                valorTotalPecas = selectedValor * selectedQtd;
                orcamento = valorTotalPecas + maoDeObra;
            }

            Object[] dados = new Object[3]; // instancia os objetos. Cada objeto representa um atributo
            dados[0] = valorTotalPecas;
            dados[1] = maoDeObra;
            dados[2] = orcamento;

            frmTotalPecas.setValue(dados[0]);
            frmTotalObra.setValue(dados[1]);
            frmOrcamentoFinal.setValue(dados[2]);
        }
    }
}
