/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.projeto.form;

import br.projeto.DAO.UsuarioDAO;
import br.projeto.data.Usuario;
import java.awt.event.WindowFocusListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        Login();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCliente = new javax.swing.JMenuItem();
        mnVeiculo = new javax.swing.JMenuItem();
        mnPecas = new javax.swing.JMenuItem();
        mnUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnNovaOS = new javax.swing.JMenuItem();
        mnServicos = new javax.swing.JMenuItem();
        mnPesquisar = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("framePrincipal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(jMenuBar1.getFont());

        jMenu1.setText("Cadastros");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnCliente.setText("Cliente");
        mnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnCliente);

        mnVeiculo.setText("Veículo");
        mnVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVeiculoActionPerformed(evt);
            }
        });
        jMenu1.add(mnVeiculo);

        mnPecas.setText("Peças");
        mnPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPecasActionPerformed(evt);
            }
        });
        jMenu1.add(mnPecas);

        mnUsuario.setText("Usuario");
        mnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Serviços");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnNovaOS.setText("Abrir Nova OS");
        mnNovaOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNovaOSActionPerformed(evt);
            }
        });
        jMenu2.add(mnNovaOS);

        mnServicos.setText("Serviços");
        mnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnServicosActionPerformed(evt);
            }
        });
        jMenu2.add(mnServicos);

        mnPesquisar.setText("Pesquisar");
        mnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPesquisarActionPerformed(evt);
            }
        });
        jMenu2.add(mnPesquisar);

        jMenuBar1.add(jMenu2);

        jMenuUsuario.setForeground(javax.swing.UIManager.getDefaults().getColor("MenuItem.disabledForeground"));
        jMenuUsuario.setText("Usuário");
        jMenuUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenuUsuario.add(mnLogout);

        jMenuBar1.add(jMenuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //JOptionPane.showConfirmDialog(this, evt, "ATENÇÃO\n\nVocê quer fechar esta aplicação?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_formWindowClosing

    private void mnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPesquisarActionPerformed
        Login();
        FrmPesquisar frmPesquisar = new FrmPesquisar();
        frmPesquisar.setVisible(true);
    }//GEN-LAST:event_mnPesquisarActionPerformed

    private void mnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnServicosActionPerformed
        Login();
        FrmServicos frmServicos = new FrmServicos();
        frmServicos.setVisible(true);
    }//GEN-LAST:event_mnServicosActionPerformed

    private void mnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuarioActionPerformed
        Login();
        FrmUsuarios frmUser = new FrmUsuarios();
        frmUser.setVisible(true);
    }//GEN-LAST:event_mnUsuarioActionPerformed

    private void mnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClienteActionPerformed
        Login();
        FrmClientes frmClientes = new FrmClientes();
        frmClientes.setVisible(true);
    }//GEN-LAST:event_mnClienteActionPerformed

    private void mnNovaOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNovaOSActionPerformed
        Login();
        FrmOS frmOs = new FrmOS();
        frmOs.setVisible(true);
    }//GEN-LAST:event_mnNovaOSActionPerformed

    private void mnVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVeiculoActionPerformed
        Login();
        FrmVeiculos frmVeiculos = new FrmVeiculos();
        frmVeiculos.setVisible(true);
    }//GEN-LAST:event_mnVeiculoActionPerformed

    private void mnPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPecasActionPerformed
        Login();
        FrmPecas frmPecas = new FrmPecas();
        frmPecas.setVisible(true);
    }//GEN-LAST:event_mnPecasActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        FrmLoginJPanel l = new FrmLoginJPanel(this, true);
        FrmLoginJPanel.setRs(false);
        l.setVisible(true);
    }//GEN-LAST:event_mnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JMenuItem mnCliente;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnNovaOS;
    private javax.swing.JMenuItem mnPecas;
    private javax.swing.JMenuItem mnPesquisar;
    private javax.swing.JMenuItem mnServicos;
    private javax.swing.JMenuItem mnUsuario;
    private javax.swing.JMenuItem mnVeiculo;
    // End of variables declaration//GEN-END:variables
public final void Login() {
        FrmLoginJPanel l = new FrmLoginJPanel(this, true);
        
        while (!l.Logado()) {

            l.setVisible(true);
        }
        l.dispose();
    }
}
